{
 "title": "Weather Forecast Computer",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Forecast (Bar Graphs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Forecast Timeframes",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "limit": "1",
     "measurement": "wu2./forecast/daypart.0.daypartName",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" }
      ],
      [
       { "params": [ "1" ], "type": "field" }
      ],
      [
       { "params": [ "2" ], "type": "field" }
      ],
      [
       { "params": [ "3" ], "type": "field" }
      ],
      [
       { "params": [ "4" ], "type": "field" }
      ],
      [
       { "params": [ "5" ], "type": "field" }
      ],
      [
       { "params": [ "6" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UV Description",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wu2./forecast/daypart.0.uvIndex",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wu2./forecast/daypart.0.windSpeed",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 0.621371" ], "type": "math" }
      ],
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 0.621371" ], "type": "math" }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 0.621371" ], "type": "math" }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 0.621371" ], "type": "math" }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 0.621371" ], "type": "math" }
      ],
      [
       { "params": [ "5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 0.621371" ], "type": "math" }
      ],
      [
       { "params": [ "6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 0.621371" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp Max",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wu2./forecast/calendarDayTemperatureMax",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp Min",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wu2./forecast/calendarDayTemperatureMin",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ],
      [
       { "params": [ "6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*9/5+32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cloud Cover",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wu2./forecast/daypart.0.cloudCover",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Precip Chance",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wu2./forecast/daypart.0.precipChance",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "QPF",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wu2./forecast/daypart.0.qpf",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "QPF Snow",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wu2./forecast/daypart.0.qpfSnow",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ],
      [
       { "params": [ "6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 25.4" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 17, "w": 17, "x": 0, "y": 47 } },
  {
   "title": "Daily Narrative",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "limit": "3",
     "measurement": "wu2./forecast/narrative",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thunder Index",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wu2./forecast/daypart.0.thunderIndex",
     "query": "SELECT last(*) FROM \"wu2./forecast/daypart.0.precipChance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Forecast Narrative", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Forecast For the Current 12h (Day if Day, Night if Night) 0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temp",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wu2./forecast/daypart.0.temperature",
       "select": [
        [
         { "params": [ "0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Wind Speed",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wu2./forecast/daypart.0.windSpeed",
       "select": [
        [
         { "params": [ "0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Forecast For the Next 12h (Night if Day, Day if Night) 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temp",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wu2./forecast/daypart.0.temperature",
       "select": [
        [
         { "params": [ "1" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Wind Speed",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wu2./forecast/daypart.0.windSpeed",
       "select": [
        [
         { "params": [ "1" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Imperial",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure (inHg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pressurehg" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "wu2.metric.pressure.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " *0.02953" ], "type": "math" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Demi-Daily Narrative",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "limit": "5",
     "measurement": "wu2./forecast/daypart.0.narrative",
     "select": [
      [
       { "params": [ "0" ], "type": "field" }
      ],
      [
       { "params": [ "1" ], "type": "field" }
      ],
      [
       { "params": [ "2" ], "type": "field" }
      ],
      [
       { "params": [ "3" ], "type": "field" }
      ],
      [
       { "params": [ "4" ], "type": "field" }
      ],
      [
       { "params": [ "5" ], "type": "field" }
      ],
      [
       { "params": [ "6" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}